#!/usr/bin/env tsx
/**
 * Capture the safety readouts a BASE tree produces for the read-differential corpus, as committed
 * expectation data.
 *
 *     pnpm capture:base-readouts                 # against origin/main
 *     pnpm capture:base-readouts --base <ref>    # against any ref
 *
 * WHY DATA RATHER THAN A LIVE COMPARISON. The XML harness next door
 * (`scripts/read-differential.ts`) imports both trees into one process and compares them live,
 * which is the right shape for a harness that generates thousands of mutated documents. This one
 * answers a narrower question about a fixed corpus, and its answer belongs in the test suite rather
 * than in a script a reviewer has to remember to run: with the base readouts committed, `pnpm test`
 * itself refuses a finding that disappeared, a `valid` that moved, or a `safeToSummarize` that went
 * the forbidden way. The script exists so the data is RE-DERIVABLE rather than hand-written: run it
 * at the same base and the file must come back byte-identical.
 *
 * `git archive` is used rather than a worktree so the materialized tree cannot pick up an untracked
 * file from the working tree, which is the failure mode that would make base look like head.
 *
 * @packageDocumentation
 */

import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { corpus, readDocument, type ReadoutCodec } from "../test/_readout-corpus.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..");
const OUT = join(REPO, "test", "__data__", "base-readouts.json");

/** The ref to capture, `--base <ref>` or `origin/main`. */
function baseRef(argv: readonly string[]): string {
  const at = argv.indexOf("--base");
  return at === -1 ? "origin/main" : (argv[at + 1] ?? "origin/main");
}

/** Materialize `src/` at `ref` into a temp directory and import it. */
async function loadBase(ref: string): Promise<{ codec: ReadoutCodec; dir: string }> {
  const dir = mkdtempSync(join(tmpdir(), "fhir-base-readouts-"));
  const archive = execFileSync("git", ["archive", ref, "src"], {
    cwd: REPO,
    maxBuffer: 256 * 1024 * 1024,
    encoding: "buffer",
  });
  execFileSync("tar", ["-x", "-C", dir], { input: archive });
  const codec = (await import(pathToFileURL(join(dir, "src", "index.ts")).href)) as ReadoutCodec;
  return { codec, dir };
}

async function main(): Promise<void> {
  const ref = baseRef(process.argv.slice(2));
  const sha = execFileSync("git", ["rev-parse", ref], { cwd: REPO, encoding: "utf8" }).trim();
  const { codec, dir } = await loadBase(ref);
  try {
    const documents: Record<string, unknown> = {};
    for (const document of corpus()) {
      documents[document.name] = readDocument(codec, document.json);
    }
    const payload = {
      note: "Generated by scripts/capture-base-readouts.ts. Do not hand-edit: re-run it instead.",
      base: sha,
      documents,
    };
    writeFileSync(OUT, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
    console.log(`captured ${String(Object.keys(documents).length)} readouts at ${sha} -> ${OUT}`);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

await main();
